# Generated by Django 5.2.6 on 2025-09-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hint_image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
