# Generated by Django 5.2.6 on 2025-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_hint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficult',
            field=models.CharField(choices=[('native', 'native'), ('student', 'student'), ('wise', 'wise')], default='student', max_length=10),
        ),
    ]
