# Generated by Django 5.2.6 on 2025-09-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz_difficult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficult',
            new_name='difficulty',
        ),
    ]
