# Generated by Django 5.2.6 on 2025-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_rename_difficult_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='stage_status',
            field=models.CharField(default='not started', max_length=100),
        ),
    ]
