# Generated by Django 5.2.6 on 2025-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quiz_stage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_choice',
            field=models.CharField(default='not started', max_length=100),
        ),
    ]
