# Generated by Django 5.2.6 on 2026-01-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_quiz_user_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='stage_status',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user_choice',
        ),
    ]
